import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { CollaborativeApp } from "@/app/CollaborativeApp";
import { Room } from "@/app/Room";
import { cn } from "@/lib/utils";
import UIWrapper from "@/components/ui/wrapper";
import { AppProvider } from "@/context/AppContext";
import ModalOrders from "@/components/dashboard/modal-orders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "scrollbar h-full scroll-smooth antialiased ",

        ` ${GeistSans.variable} ${GeistMono.variable}`,
      )}
    >
      <body className="  h-full bg-zinc-900 text-white">
        {/* <ProgressBar />
      <Nav /> */}
        <AppProvider>
          <UIWrapper>{children}</UIWrapper>
          <ModalOrders />
        </AppProvider>
      </body>
    </html>
  );
}
